### ISSUE TITLE
Daily Data Calculation and Roll

### ISSUE THREAD

**Issue by AZDavid2** [nyanginator/wrtbwmon-remixed#1]
Total Used and Average Daily Total columns appear to be calculating data correctly.  Today Total columns as well as Grand Total bar along the top are not adding up.  Reinstalled the tool today after after seeing the discrepancy for several days.  After reinstalling, received the same issue.  I am running the tool from DD-WRT v3.0-r44251 std (08/27/20).

Screenshot showing usage.  Being first day reinstalled expect Today Total to equal Total Used.  Also, total bar along the top is not adding properly.
![wrtbwmon-remixed usage screenshot](https://user-images.githubusercontent.com/70821701/92313513-60148a80-ef81-11ea-9a04-7d15e9eedc2d.jpg)

**Comment by nyanginator** [comment]
Hi, your .db files seem to be out-of-sync. Try starting over by doing a reset:

`$ /tmp/mnt/sda1/reset`

If you are able to reproduce the error again, let me know what steps you took to do it.

**Comment by AZDavid2** [comment]
Ran the reset.  Columns are still not cooperating.

![wrtbwmon-remixed usage screenshot - after reset](https://user-images.githubusercontent.com/70821701/92318540-7f7fd780-efc2-11ea-9b27-a1d5e0796ff5.jpg)

**Comment by AZDavid2** [comment]
Is this a normal response when running the reset?

![invalid number](https://user-images.githubusercontent.com/70821701/92332122-22bb0600-f030-11ea-9dc4-5f3eb6c7d002.jpg)

**Comment by nyanginator** [comment]
I'm having trouble reproducing the error, so it's somewhat difficult for me to debug. Initially, it looks like your `/tmp/usage.db` and `/tmp/reports/*daily.db` aren't getting the correct values. It may be as simple as the USB failing on read/write (a problem I had before) ... or something else.

The Grand Total/Down/Up on the top is calculated [here](https://github.com/nyanginator/wrtbwmon-remixed/blob/2395b88732ac00839e8fc1f63ad7d11465cff808/wrtbwmon#L766), which is pulling straight from `/tmp/usage.db`. Numbers for Today are always pulled from the `/tmp/reports/*daily.db` files, [here](https://github.com/nyanginator/wrtbwmon-remixed/blob/2395b88732ac00839e8fc1f63ad7d11465cff808/wrtbwmon#L895) and [here](https://github.com/nyanginator/wrtbwmon-remixed/blob/2395b88732ac00839e8fc1f63ad7d11465cff808/wrtbwmon#L862).

Any other hints you can provide might help to pinpoint the problem:

- Is there any error output when running commands from the prompt?
- Do the numbers initially start out correct (according to what you have downloaded/uploaded)? Try doing `/tmp/mnt/sda1/reset`, download something, and then use the `/tmp/mnt/sda1/unp` to force update/publish and see the numbers.
- Do the Total numbers stay correct?
- How do the numbers change when updated (e.g. when you download a 10 MB file, how much is added to Total and how much is added to Today)? Use `/tmp/mnt/sda1/unp` to update/publish right away.
- When you reset, are all of the numbers correctly zeroed out (in the `/tmp/reports/*.db` and `/tmp/usage.db` files)?
- Did you reboot the router?
- What router model do you have?
- Did you customize settings on the router? Other things running that might interfere with writing to .db files?
- Have you tried with a different USB key? Does your USB have enough free space? Try a different USB port?
- Do the graph numbers match the table?
- Which lines do you have in cron?
- Are there leftover `/tmp/*.tmp` files? Usually an indicator that the script is failing somewhere.
- etc.

If you want to do refresh everything manually, you can:

`$ rm -rf /tmp/usage.db /tmp/reports /tmp/www/reports /tmp/www/usage.htm`

And remove any previous backups made:

`$ rm -rf /tmp/mnt/sda1/reports /tmp/mnt/sda1/usage.db /tmp/mnt/sda1/monthlybkup /tmp/mnt/sda1/bkup`

**Comment by nyanginator** [comment]
> Is this a normal response when running the reset?
> 
> ![invalid number](https://user-images.githubusercontent.com/70821701/92332122-22bb0600-f030-11ea-9dc4-5f3eb6c7d002.jpg)

Ah, well that definitely seems to be [a/the] problem. The .db files are likely not getting updated correctly if the script is exiting early.

**Comment by nyanginator** [comment]
Do you get any output from this?

`$ dmesg | head -n -1`

**Comment by AZDavid2** [comment]
Same invalid number message

![invalid number 2](https://user-images.githubusercontent.com/70821701/92332573-c4902200-f033-11ea-8d2f-1c2e90ede60f.jpg)

Have a brand new 16 GB USB drive showing up later today.  Going to give that a try.  Does it matter how the drive is formatted?

**Comment by nyanginator** [comment]
Huh, that's interesting indeed. I don't know if the build for your router is somehow compiled in a way that makes the `head` command work differently. `head -n -1` appears twice in the script, so it needs to work. Maybe play around with:

`$ dmesg | head -n-1` (no space)
`$ dmesg | head -n "-1"` (quotes)
`$ dmesg | head -n"-1"` (quotes with no space)

Try a number other than -1 and see how it behaves. All these commands work fine for me (also the r44251 build).

My drive is formatted as FAT32, but I can't imagine that or the drive itself affecting the shell. The `head` command should work regardless of the USB. You may want to try re-flashing or flashing a different DD-WRT build to see if was a regression in this version.

**Comment by AZDavid2** [comment]
I am running DD-WRT on a Linksys WRT32x, accessing the router through a PuTTY SSH session

Tried several options to see if I could isolate a cause
- Installed the tool on a completely new USB drive formatted FAT32
- Reset router settings to factory default
- Stepped back the firmware version back to a prior year

No change after all three - received either "invalid number" or "unrecognized option" when running reset or unp

Following was returned after a clean install.  Could this help point in a direction?
![clean install](https://user-images.githubusercontent.com/70821701/92335591-0bd6dc80-f04d-11ea-8884-066f2d28c640.jpg)

Tried playing around with the commands including using a number other than -1
![trying other options](https://user-images.githubusercontent.com/70821701/92335593-0e393680-f04d-11ea-8465-bf28b43f1f20.jpg)

**Comment by AZDavid2** [comment]
Is there a way I can open the database files?  

Attempted to open using SQLite but they are not being recognized as a database.

**Comment by nyanginator** [comment]
Looks like there's more than one shell command with issues. Guessing that this won't work for you either:

`$ date -d @1599429351`

I haven't found anything yet in the DD-WRT forums about this. Might be worth posting there to see if anybody else has had a similar issue. Maybe [erasing NVRAM](https://wiki.dd-wrt.com/wiki/index.php/Hard_reset_or_30/30/30#Erasing_NVRAM) could help?

The .db files generated by the script are just text files, so you can open them with vi.

**Comment by nyanginator** [comment]
Found [this thread](https://forum.dd-wrt.com/phpBB2/viewtopic.php?t=315569). Did you upgrade to the "full featured" version?

**Comment by AZDavid2** [comment]
Yes, I installed the full version ddwrt-linksys-wrt32x-webflash.bin.  

Going to perform a hard reset soon to see if that works.

Entering $ date -d @1599429351 worked
![time](https://user-images.githubusercontent.com/70821701/92343413-836e3100-f078-11ea-944e-ab4c46afd945.jpg)

**Comment by AZDavid2** [comment]
No luck after the hard reset to clear NVRAM.  At a complete loss for what to try next.

**Comment by nyanginator** [comment]
Just spitballing some ideas here:

- It might be a [whitespace/CR issue](https://www.unix.com/unix-for-dummies-questions-and-answers/263828-shell-script-not-working-but-command-works-command-prompt.html)? Did the script files possibly change depending on how you copied the scripts over? When you `$ vi /tmp/mnt/sda1/wrtbwmon`, do you see [^M characters](https://www.networkworld.com/article/3438857/how-to-remove-carriage-returns-from-text-files-on-linux.html)?
- Check your client [(PuTTY) settings](https://www.ssh.com/ssh/putty/putty-manuals/0.68/Chapter4.html). For example, although a different program: [this](https://superuser.com/questions/1283755/why-are-ssh-commands-not-working). And check out [here](https://stackoverflow.com/questions/11997108/what-does-putty-send-when-i-press-enter-key), and [here](https://www.geeksforgeeks.org/dos2unix-unix2dos-commands/).
- [This post](https://serverfault.com/questions/604709/ways-to-automatically-fix-line-endings-in-shell-scripts-or-files-who-break-with) sounds like a similar problem (broken scripts and "invalid option" errors).
- Do you have a different router to test on?
- Or can you try just telnetting in from a command prompt (remember to enable Telnet in DD-WRT) instead of using PuTTY?
- Can also try posting to the [DD-WRT forum](https://forum.dd-wrt.com/phpBB2).

**Comment by AZDavid2** [comment]
Ruled out PuTTY by setting up Telnet through command prompt in Windows.  Receive the same command responses.

Do not see any ^M characters when running `$ vi /tmp/mnt/sda1/wrtbwmon`
![m search](https://user-images.githubusercontent.com/70821701/92415930-eced4e80-f10f-11ea-80b3-3e3a0bcd3ff5.jpg)

Suspected a date issue so I ran the "date" command from DD-WRT.  Router responded with the correct date and time.
![command](https://user-images.githubusercontent.com/70821701/92415729-25405d00-f10f-11ea-9a21-c1ae96abc96d.jpg)

Going to start a thread on the DD-WRT forum to see if anyone there has ideas.

Thank you for all your continued help!  Much appreciated!

**Comment by nyanginator** [comment]
Seems a router/DD-WRT issue and not the script.
